#!/bin/bash

expecting_n_args() {
	if [[ $1 -ne $2 ]]; then
		echo "Wrong number of arguments, expecting $1, got $2"
		exit 1
	fi
}

processed_file_name() {
	expecting_n_args 1 "$#"
	OUTDIR="$(dirname "$1")/ready"
    mkdir -p "$OUTDIR"
    echo "$OUTDIR/$(basename "$1")"
}

lufs_youtube() {
	expecting_n_args 1 "$#"

	IN="$1"
	OUT="$1_$(date '+%s')"

	# First pass
	MEASURED=$(ffmpeg -i "$IN" -af "loudnorm=print_format=json" -f null - 2>&1 |
		grep -P 'input_i|input_tp|input_lra|input_thresh' |
		perl -ne 'm/"input(.+?)"\s+:\s+"(.+?)"/; print ":measured$1=$2"')

	# Actual loudness normalization
	ffmpeg -i "$IN" -af "loudnorm=i=-14:tp=-1:lra=11$MEASURED" "$OUT" && mv "$OUT" "$IN"
}

denoise_norm() {
	expecting_n_args 2 "$#"

	IN="$1"
	OUT="$2"

	sox "$IN" -n trim 0 5 noiseprof |
		sox "$IN" -t wav "$OUT" noisered - 0.3 silence 1 0.1 -50d norm -0.1
}

OUTFILE=$(processed_file_name "$1")
denoise_norm "$1" "$OUTFILE"
