#!/bin/bash 
pid=$(pgrep '^ffmpeg')

if [ -z "$pid" ]; then
    exit 1 # replace with system notification
fi

status=$(ps -o stat= -p "$pid")

case $status in
    *T*) kill -SIGCONT "$pid"
         echo "Resumed FFmpeg." ;;
    *)   kill -SIGSTOP "$pid"
         echo "Paused FFmpeg." ;;
esac
