#!/bin/bash

INPUT_DEV='default:CARD=H5'

read -r -d '' USAGE <<EOI

    talk

    Records audio with ffmpeg directly to your computer

    The recording is stored in zero-padded, serialized files,
    like 00006.wav

    Usage:
        $0 [-i <device> ] <output directory>

    Options:
        -i recording device name, defaults to $INPUT_DEV
           To find your device, run arecord -L

EOI

exit_with_error() {
	echo "$1"
	echo "$USAGE"
	exit 1
}

next_file() {
	local RECDIR="$1"
	# shellcheck disable=SC2012
	N=$(ls -t "$RECDIR" 2>/dev/null | sed '1s/\..*//; q')
	if [ -z "$N" ]; then
		N=0
	fi
	printf "${RECDIR}/%05d.wav" $((N + 1))
}

while getopts 'i:' name; do
	case "$name" in
	i)
		INPUT_DEV="$name"
		;;
	*)
		exit_with_error "Invalid option $name"
		;;
	esac
done

shift $((OPTIND - 1))

if [[ $# -ne 1 ]]; then
	exit_with_error "Illegal number of arguments"
fi

RECDIR="$1"
mkdir -p "$RECDIR"

OUTFILE=$(next_file "$RECDIR")

echo "Recording to: $OUTFILE"
echo "Using device: $INPUT_DEV"

ffmpeg -f alsa -channels 1 -ar 48000 -i "$INPUT_DEV" -af "pan=stereo|c0=c0|c1=c0" "$OUTFILE"
